### ISSUE TITLE
wrong psr4 autoload and use @app instead @frontend ini SitemapTrait

### ISSUE THREAD

**Issue by bahirul** [odanylevskyi/yii2-sitemap-xml#1]
I found two issue :

1. wrong psr4 caused error class loading.

2. use `@app` alias instead `@frontend`, if user use basic template app `@frontend` alias in not predefined.

**Comment by bahirul** [comment]
Please see my PR #2 .

**Comment by odanylevskyi** [comment]
Thanks. Will take a look shortly.
